###########################################
# Iceberg - Nessie Setup
###########################################

version: "3"

services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    platform: linux/arm64
    container_name: nessie
    networks:
      iceberg:
    ports:
      - 19120:19120
    environment:
      - nessie.version.store.type=IN_MEMORY
      - nessie.catalog.default-warehouse=warehouse
      - nessie.catalog.warehouses.warehouse.location=s3://iceberg-datalake/
      - nessie.catalog.service.s3.default-options.endpoint=http://minio:9000/
      - nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      - nessie.catalog.service.s3.default-options.path-style-access=true
      - nessie.catalog.service.s3.default-options.auth-type=STATIC
      - nessie.catalog.secrets.access-key.name=minioadmin
      - nessie.catalog.secrets.access-key.secret=minioadmin
      - nessie.catalog.service.s3.default-options.region=us-east-1
      - nessie.server.authentication.enabled=false
  # Minio Storage Server
  minio:
    image: docker.io/minio/minio:latest
    platform: linux/arm64
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      iceberg:
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
  # Dremio
  dremio:
    platform: linux/arm64
    image: docker.io/dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
    container_name: dremio
    networks:
      iceberg:
  lambda:
    image: localhost/iot-file-processor:latest
    platform: linux/arm64
    container_name: lambda
    ports:
      - "9090:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin  # <-- Add for boto3 compatibility
      AWS_SECRET_ACCESS_KEY: minioadmin  # <-- Add for boto3 compatibility
    networks:
      iceberg:
networks:
  iceberg:
